################################################################
#
# Pipeline pipeline_trna.py configuration file
#
# This pipeline.yml file lists some configuration options that you
# need to set before running the pipeline. 
#
################################################################

# Location of the cribbslab directory
cribbslab: '/ifs/projects/adam/cribbslab/'

# Project name
projectname: proj001

# Copyright statement
copyright: Cribbs Group, Botnar Research Centre (2018)

##########################################################
# Location of the ensembl gtf
##########################################################

# Full diectory of the gtf
gtf_location: /ifs/projects/proj051/Analysis_will_paper/tRNA/Homo_sapiens.GRCh38.92.gtf.gz

trna_scan_load: 0

##########################################################
# UCSC database options
# This section controls the parameters required for
# repeats from the ucsc
##########################################################

ucsc:
# UCSC database host
    host: genome-mysql.cse.ucsc.edu

# UCSC database user name
    user: genome

# UCSC database name
    database: hg38

# repeats to collect as ',' separated list
    repeattypes: DNA,LINE,SINE,LTR,Transposon

# RNA repeats to collect as ',' separated list
    rnatypes: RNA,rRNA,scRNA,snRNA,srpRNA,tRNA

# comma separated list of regular expressions (a word contained in the contig that defines the contigs to be removed) 
# for contigs (ensembl nomenclature)
# to be removed from ensembl_filename_gtf during genome
# sanitization
    remove_contigs: [random,chrUn,na,alt]


################################################################
# trimmomatic options
################################################################
trimmomatic:
# http://www.usadellab.org/cms/?page=trimmomatic

# specify with 1 or 0 if trimmomatic should be ran
    run: 0

#options
    options: LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36

# specify the phred score as per trimmomatic documentation
    phred: -phred33

# if adapter removal is required, specify the location of a fasta file
# containing adapters and define the adapter parameters
# this variable will be overriden if auto_remove != 0
    adapter: /ifs/apps/bio/trimmomatic-0.32/adapters/TruSeq2-PE.fa

# max mismatches in adapter sequence
    mismatches: 1

# accuracy thresholds. these values are (very roughly speaking) log-10
# probabilities of getting a match at random
# A threshold of 10 requires a perfect match of ~17bp (see above website)
    c_thresh: 10

# only used in paired end mode
    p_thresh: 30

########################################################
# the genome to use (UCSC convention)
########################################################

# The name of the genome (single word with no "_" or "-" and including a number, without the .fa. e.g. hg19, genome1)
genome: hg38

# The folder that the genome is located in
genome_dir: /ifs/mirror/genomes/index/

##########################################################
# location of a bowtie2 indexed genome
# for infomation on how to build this please refer to: http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#getting-started-with-bowtie-2-lambda-phage-example
##########################################################

bowtie:
    genome : hg38

    genome_dir: /ifs/mirror/genomes/bowtie/

    options: --local --very-sensitive-local
###########################################################
# Differential expression
###########################################################

diff_eprs:
    # This is the design formula to use for DESeq2
    design: ~Condition
    # Select the column with the contrast for your analysis
    value: Condition
    # Select the control
    control: Condition1
    # Select the test value
    test: Condition2 